apiVersion: apps/v1
kind: Deployment
metadata:
  name: sicst-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sicst-front
  template:
    metadata:
      labels:
        app: sicst-front
    spec:
      containers:
      - name: sicst-front
        image: iuda194/sicst_front:prod
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: sicst-front-svc
spec:
  type: NodePort
  selector:
    app: sicst-front
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30002